"""Interactive Recursive Tree and Knowledge Graph Visualizer."""
from __future__ import annotations

import html
from typing import Any, Dict, List


def generate_mermaid_tree(state: Dict[str, Any]) -> str:
    """Construct dynamic Mermaid graph syntax representing the recursive execution DAG."""
    topic = state.get("topic", "Research Topic")
    sub_questions = state.get("sub_questions", [])
    sources = state.get("sources", [])
    depth = state.get("recursion_depth", 0)

    clean_topic = html.escape(topic[:35] + ("..." if len(topic) > 35 else ""))

    lines = ["graph TD", f'    Root["🎯 {clean_topic}"]:::topicStyle']

    for i, sq in enumerate(sub_questions):
        sq_id = f"Q{i+1}"
        sq_text = html.escape(sq.get("question", "")[:45] + "...")
        status = sq.get("status", "pending")
        conf = float(sq.get("confidence_score", 0.0)) * 100

        lines.append(f'    Root --> {sq_id}["❓ {sq_id}: {sq_text}<br/><b>Confidence: {conf:.0f}%</b>"]:::sqStyle')

        # Link to sources if referenced
        source_ids = sq.get("source_ids", [])
        for sid in source_ids[:2]:
            matching = [s for s in sources if s.get("id") == sid]
            if matching:
                src_title = html.escape(matching[0].get("title", "Source")[:25] + "...")
                lines.append(f'    {sq_id} --> S_{sid}["📄 {src_title}"]:::srcStyle')

    # Add recursive loop indicator if depth > 1
    if depth > 1:
        lines.append('    Verifier["🔍 Verifier Audit"]:::auditStyle')
        lines.append(f'    Q{len(sub_questions)} --> Verifier')
        lines.append('    Verifier -.->|"Recursive Loop"| Root')

    lines.extend([
        "    classDef topicStyle fill:#1e293b,stroke:#3b82f6,stroke-width:2px,color:#fff;",
        "    classDef sqStyle fill:#0f172a,stroke:#10b981,stroke-width:1px,color:#e2e8f0;",
        "    classDef srcStyle fill:#1e1b4b,stroke:#8b5cf6,stroke-width:1px,color:#c7d2fe;",
        "    classDef auditStyle fill:#312e81,stroke:#f59e0b,stroke-width:2px,color:#fef3c7;",
    ])

    return "\n".join(lines)


def render_tree_view(st: Any, state: Dict[str, Any]) -> None:
    """Render the interactive recursive tree and sub-question breakdown."""
    st.subheader("🌳 Recursive Inquiry Tree & Evidence Graph")
    st.caption("Hierarchical decomposition generated by Prime Supervisor and worker agents.")

    mermaid_code = generate_mermaid_tree(state)
    st.markdown(f"```mermaid\n{mermaid_code}\n```")

    # Detailed Sub-Inquiry Inspector
    st.write("#### 🔎 Sub-Inquiry Deep Dive")
    sub_questions = state.get("sub_questions", [])
    if not sub_questions:
        st.info("No sub-questions generated yet.")
        return

    for idx, sq in enumerate(sub_questions, 1):
        q_title = sq.get("question", f"Question {idx}")
        conf = float(sq.get("confidence_score", 0.0)) * 100
        status_emoji = "✅" if sq.get("status") in ("researched", "verified") else "⏳"

        with st.expander(f"{status_emoji} Question {idx}: {q_title} (Confidence: {conf:.0f}%)", expanded=False):
            st.markdown(f"**Strategic Rationale:** {sq.get('rationale', 'N/A')}")
            st.markdown(f"**Status:** `{sq.get('status', 'pending')}`")
            st.markdown(f"**Verified Findings:**\n{sq.get('findings', 'No findings collected.')}")

            sids = sq.get("source_ids", [])
            if sids:
                st.markdown(f"**Attributed Source IDs:** `{'`, `'.join(sids)}`")
