"""Typed schemas and LangGraph state representations for recursive research execution."""
from __future__ import annotations

import time
import uuid
from typing import Any, Dict, List, Optional
from typing_extensions import TypedDict

try:
    from pydantic import BaseModel, Field

    class Source(BaseModel):
        """Metadata and content for an ingested web or document source."""
        id: str = Field(default_factory=lambda: str(uuid.uuid4())[:8])
        url: str
        title: str
        snippet: str
        relevance_score: float = 1.0
        retrieved_at: float = Field(default_factory=time.time)

    class SubQuestion(BaseModel):
        """Structured sub-inquiry decomposed by the Prime Agent."""
        id: str = Field(default_factory=lambda: str(uuid.uuid4())[:8])
        question: str
        rationale: str
        status: str = "pending"  # pending, researched, verified, failed
        findings: Optional[str] = None
        confidence_score: float = 0.0
        source_ids: List[str] = Field(default_factory=list)

    class VerificationAssessment(BaseModel):
        """Critique and hallucination evaluation generated by the Verifier Agent."""
        sufficient: bool
        hallucination_score: float = 0.0  # 0.0 = grounded, 1.0 = highly hallucinated
        confidence_score: float = 0.0    # 0.0 = low confidence, 1.0 = high certainty
        reasoning: str
        unresolved_gaps: List[str] = Field(default_factory=list)
        suggested_followups: List[str] = Field(default_factory=list)

    class ResearchReport(BaseModel):
        """Final synthesized research intelligence deliverable."""
        title: str
        executive_summary: str
        sections: Dict[str, str] = Field(default_factory=dict)
        key_findings: List[str] = Field(default_factory=list)
        citations: List[Dict[str, str]] = Field(default_factory=list)
        token_savings_estimate: float = 0.35

except ImportError:
    # Graceful fallback dataclasses when pydantic is not present
    from dataclasses import dataclass, field

    @dataclass
    class Source:  # type: ignore[no-redef]
        url: str
        title: str
        snippet: str
        id: str = ""
        relevance_score: float = 1.0
        retrieved_at: float = 0.0

        def __post_init__(self) -> None:
            if not self.id:
                self.id = str(uuid.uuid4())[:8]
            if not self.retrieved_at:
                self.retrieved_at = time.time()

        def model_dump(self) -> dict[str, Any]:
            return {
                "id": self.id,
                "url": self.url,
                "title": self.title,
                "snippet": self.snippet,
                "relevance_score": self.relevance_score,
                "retrieved_at": self.retrieved_at,
            }

    @dataclass
    class SubQuestion:  # type: ignore[no-redef]
        question: str
        rationale: str
        id: str = ""
        status: str = "pending"
        findings: Optional[str] = None
        confidence_score: float = 0.0
        source_ids: List[str] = field(default_factory=list)

        def __post_init__(self) -> None:
            if not self.id:
                self.id = str(uuid.uuid4())[:8]

        def model_dump(self) -> dict[str, Any]:
            return {
                "id": self.id,
                "question": self.question,
                "rationale": self.rationale,
                "status": self.status,
                "findings": self.findings,
                "confidence_score": self.confidence_score,
                "source_ids": self.source_ids,
            }

    @dataclass
    class VerificationAssessment:  # type: ignore[no-redef]
        sufficient: bool
        reasoning: str
        hallucination_score: float = 0.0
        confidence_score: float = 0.0
        unresolved_gaps: List[str] = field(default_factory=list)
        suggested_followups: List[str] = field(default_factory=list)

        def model_dump(self) -> dict[str, Any]:
            return {
                "sufficient": self.sufficient,
                "hallucination_score": self.hallucination_score,
                "confidence_score": self.confidence_score,
                "reasoning": self.reasoning,
                "unresolved_gaps": self.unresolved_gaps,
                "suggested_followups": self.suggested_followups,
            }

    @dataclass
    class ResearchReport:  # type: ignore[no-redef]
        title: str
        executive_summary: str
        sections: Dict[str, str] = field(default_factory=dict)
        key_findings: List[str] = field(default_factory=list)
        citations: List[Dict[str, str]] = field(default_factory=list)
        token_savings_estimate: float = 0.35

        def model_dump(self) -> dict[str, Any]:
            return {
                "title": self.title,
                "executive_summary": self.executive_summary,
                "sections": self.sections,
                "key_findings": self.key_findings,
                "citations": self.citations,
                "token_savings_estimate": self.token_savings_estimate,
            }


class ResearchState(TypedDict):
    """The central state graph contract passed through the recursive LangGraph engine."""
    topic: str
    recursion_depth: int
    max_recursion_depth: int
    sub_questions: List[Dict[str, Any]]
    sources: List[Dict[str, Any]]
    collected_evidence: List[str]
    verification_history: List[Dict[str, Any]]
    is_complete: bool
    final_report: Optional[str]
    trace_logs: List[Dict[str, Any]]
    error_log: List[str]
